stages:
  data_ingestion:
    cmd: python data_ingestion.py
    deps:
    - data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python data_preprocessing.py
    deps:
    - data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python feature_engineering.py
    deps:
    - feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features
  model_building:
    cmd: python model_building.py
    deps:
    - model_building.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    outs:
    - model.pkl
  model_evaluation:
    cmd: python model_evaluation.py
    deps:
    - model_evaluation.py
    metrics:
    - metrics.json
